name = "craftstats"
main = "src/index.ts"
compatibility_date = "2022-07-01"

kv_namespaces = [
    { binding = "KV_SERVERS", id = "" },
]

[vars]
# Retry when server ping failed
PING_ATTEMPTS = 2

WEBHOOK_URL = ""
# By default stats in the indivudal servers charts are deleted after 2 hours (120 min)
RECENT_CHARTS_DELETE_AFTER_MINUTES = 120

# By default the global server chart will have data
# with a 15 min interval
GLOBAL_CHART_PING_INTERVAL = 15
# By default stats in the global server chart are deleted after 6 months (180 days)
GLOBAL_CHART_DELETE_AFTER_DAYS = 180

# You can define a token to edit the servers from the /edit page
# The token should be at least 10 characters
SERVERS_EDIT_TOKEN = ""

# You can define an URL if you use a ping function on Scaleway
# This is required to add Minecraft Bedrock servers
# PING_FUNCTION_URL = "https://xxx-ping.functions.fnc.fr-par.scw.cloud"

[triggers]
crons = ["*/5 * * * *"]

[site]
bucket = "./frontend/dist"
